---
# handlers file for zookeeper

- name: Enable service zookeeper
  ansible.builtin.systemd:
    name: zookeeper
    enabled: True
    masked: False

- name: daemon reload
  ansible.builtin.systemd:
    name: zookeeper.service
    state: restarted
    daemon-reload: True
  become: True
...