version: '3'

services:
  semaphore:
    ports:
      - "3000:3000"
    image: ansiblesemaphore/semaphore:latest
    container_name: semaphore
    environment:
      SEMAPHORE_DB_USER: root
      SEMAPHORE_DB_PASS: password
      SEMAPHORE_DB_HOST: db
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: mydb
      SEMAPHORE_PLAYBOOK_PATH: ./semaphore/
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@example.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: MflCLIUF5bn6Lgkuwy4BoAdIFhoZ4Ief2oocXmuZSjs=
    depends_on:
      - db

  controller:
    hostname: controller
    build:
      context: ./
      dockerfile: Dockerfile-ansible
    ports:
      # SSH
      - "2220:22"
      # ttyd
      - "4200:4200"
      # dashboard
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./ansible:/home/vagrant/ansible

  server1:
    hostname: server1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2221:22"
      - "4201:4200"

  server2:
    hostname: server2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2222:22"
      - "4202:4200"

  server3:
    hostname: server3
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2223:22"
      - "4203:4200"

  db:   
    image: arm64v8/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"