---
- hosts: all
  roles:
    - role: java
      tags:
        - zookeeper
        - kafka

- hosts: zookeeper
  roles:
    - role: zookeeper
      tags:
        - zookeeper
        - java

- hosts: kafka
  roles:
    - role: kafka
      tags:
        - kafka
        - java
...